# Heroku doesn't seem to fully support multi-stage builds yet
FROM golang:1.13.5-alpine

# Enable Go modules
ENV GO111MODULE=on
# Install Git so `go get` works
RUN apk add --no-cache git
# Install the Certificate-Authority certificates to enable HTTPS
RUN apk add --no-cache ca-certificates

COPY ./ .
RUN go mod tidy
RUN go build -a .

CMD ["sabacc"]
